# ###################################################
#            Lyttle Nametag - config.yml            #
# ###################################################
# This file contains the configuration for the Lyttle Nametag plugin.
# You can customize the nametag format and other settings.
#
# ‚ö†Ô∏è Do NOT remove any keys ‚Äî the plugin depends on them.
# You are free to customize the text and formatting.
# ###################################################

# nametag
nametag: |-
  <gray>%luckperms_prefix%</gray>
  <gray><PLAYER></gray>
  <dark_gray>@</dark_gray>
  <yellow>%vault_eco_balance_formatted%</yellow> <gold>Tokens</gold>
  <red>üñ§ %math_0:0_({player_health})%<dark_grey>/20

# Interval in seconds for checking updates.
interval: 0.5

# The maximum distance at which the nametag will be visible. (In blocks) (default: 64)
view_distance: 64

# ‚ö†Ô∏è Do not change this value.
config_version: 3
